#------------------------------------------------------------------
# CONFIGURAZIONE PER AMBIENTE STAGING (TESTATO DA UTENTE)
#------------------------------------------------------------------ 
#
#------------------------------------------------------------------  
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10000MB
      max-request-size: 10000MB
  jpa:
    #show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.format_sql: true
      hibernate.default_schema: cdst
    hibernate:
    #none, validate, update, create
      ddlAuto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 
    username: 
    password: 
  #FLYWAY enabled = true per lanciare flyway:migrate all'avvio del server. 
  # Per gli altri comandi (info, repair, ...) utilizzare il maven plugin (per questo configurare connessione db anche nel pom.xml per flyway-maven-plugin)
  flyway:
    enabled: false
    baseline-on-migrate: true
    schemas: cdst
    out-of-order: true
    ignore-missing-migrations: true
    
mail:
    defaultFormatPec: true
    qualifierStrategy: regione_marche
    default-encoding: UTF-8
    host: webmail.regione.marche.it
    pop3: 
      host:
      port:
      folder:
    from: noreply.meetpad@regione.marche.it
    username: 
    password: 
    port: 25
    protocol: smtp
    smtp:
      debug: true
      auth: true
      ehlo: false
      starttls:
        required: false
        enable: false
      socketFactory:
        fallback: false                         
        required: false                 
    test-connection: false
    baseUrlIndizione: https://meetpad.regione.marche.it/join
    urlDocumentazione: https://meetpad.regione.marche.it/authInstructions.pdf
    sendEnabled: true
    recipient: 
      fake: false
      fakeAddress: guido.deluca@postaraffaello.it
mailPec:
    host: smtps.emarche.it
    pop3: 
      host: pop3s.emarche.it
      port: 995
      folder: Inbox
    from: meetpad@emarche.it
    username: 
    password: 
    port: 465
    enableAsyncCheckMailStatus: true
    enableAsyncReinoltroMailInErrore: false    
#------------------------------------------------------------------
#
#------------------------------------------------------------------  
file:
  upload-dir: ./uploads
  upload-subdir: ./${cfAmministrazioneProcedente}/${idConferenza}
  token-expire-minutes: 30
  download-context-path: https://meetpad.regione.marche.it/mpad-rest/1.0/
autenticazione:
  utente-fittizio: false
  cf-utente-fittizio: 
  verifica-token: false
  token-filter-exclude-urls: /actuator/httptrace,/v2/api-docs
management:
  endpoints:
    web:
      exposure:
        include: httptrace
  trace:
    http:
      enabled: true
#------------------------------------------------------------------
#
#------------------------------------------------------------------        
jwt:
  urlpublickey: src/main/resources/certificates/PublicAOuthCertified.pem
  tokenWSO2JWTClass: TokenJWT_min
#------------------------------------------------------------------
#
#------------------------------------------------------------------  
messages:
  properties: classpath:messages 

protocollo:
 utenteprotocollo: 
  